name: Docker Image CI

on: [push]

jobs:
  x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang-7, clang-8, clang-9, gcc-7, gcc-8, gcc-9]
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/x86_64-unknown-linux-gnu
        tags: ${{ matrix.compiler }}
        file: x86_64-unknown-linux-gnu:${{ matrix.compiler }}/Dockerfile

  mips-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9]
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/mips-unknown-linux-gnu
        tags: ${{ matrix.compiler }}
        file: mips-unknown-linux-gnu:${{ matrix.compiler }}/Dockerfile

  powerpc-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9]
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/powerpc-unknown-linux-gnu
        tags: ${{ matrix.compiler }}
        file: powerpc-unknown-linux-gnu:${{ matrix.compiler }}/Dockerfile

  powerpc64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9]
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/powerpc64-unknown-linux-gnu
        tags: ${{ matrix.compiler }}
        file: powerpc64-unknown-linux-gnu:${{ matrix.compiler }}/Dockerfile

  powerpc64le-unknown-linux-gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-9]
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/powerpc64le-unknown-linux-gnu
        tags: ${{ matrix.compiler }}
        file: powerpc64le-unknown-linux-gnu:${{ matrix.compiler }}/Dockerfile
